version: "3.7"

services:
  exrx-net-crawler:
    container_name: exrx-net-crawler-stage
    image: "ijohnnymiller/exrx-net-crawler-stage:${TAG}"
    build:
      dockerfile: Dockerfile
      context: .
      args:
        ENV: stage
        ENV_ALIAS: stage
    ports:
      - 8081:80
    volumes:
      - /Users/johnny/docker-file-mapping/exrx-net-crawler/log:/var/log/nginx
